all:
	g++-4.8 -std=c++11 -O3 -g -Wall -w -framework OpenCL -framework OpenGL -fopenmp -I../CL main.cpp ../CL/oclUtils.cpp ../CL/shrUtils.cpp ../CL/cmd_arg_reader.cpp bmploader.cpp sdf.cpp Individual.cpp
